# Generated by Django 4.2.3 on 2023-07-18 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='income',
            name='recurring_frequency',
        ),
    ]
