# Generated by Django 4.2.3 on 2023-07-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_remove_income_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
